"""SnapTrade backend — the only place that translates ``St*`` types into the
neutral ``finstore.model.*`` types.

The normalization seam mirrors ``SimpleFINBackend`` in structure:
  - ``SnapTradeCredentials`` holds all credential material
  - ``SnapTradeBackend.fetch_and_persist`` drives the API calls and calls
    ``storage.merge_chunk`` with a fully normalized ``StorageChunk``
  - ``St*`` types never cross this module boundary

Fetch strategy:
  1. Load brokerage authorizations → build auth_id → slug map for ``conn_id``
  2. Load all accounts
  3. For each date window in [dtstart, dtend], fetch activities for all accounts
  4. Fetch current balances + positions for all accounts (one API call each)
  5. Build one ``InvestmentAccount`` per account with all accumulated data
  6. Collect all referenced securities
  7. Single ``storage.merge_chunk`` call with the complete ``StorageChunk``
"""
from __future__ import annotations

import logging
import time
from dataclasses import dataclass
from datetime import date, datetime, timezone
from collections import OrderedDict
from decimal import Decimal
from typing import TYPE_CHECKING

import httpx

from finstore.backends.snaptrade.client import StClient
from finstore.backends.snaptrade.models import (
    StAccount,
    StActivity,
    StBalance,
    StBrokerageAuthorization,
    StPosition,
    StSymbol,
)
from finstore.model import (
    Connection,
    InvestmentAccount,
    InvestmentTransaction,
    Position,
    Security,
    StorageChunk,
)
from finstore.storage.paths import normalize_conn_id, sanitize_account_name

if TYPE_CHECKING:
    from finstore.protocols import Storage

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Credentials
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SnapTradeCredentials:
    """Two-level SnapTrade credentials.

    Partner-level (``client_id``, ``consumer_key``) come from env vars.
    Per-user (``user_id``, ``user_secret``) are generated by SnapTrade on
    registration and stored as a JSON blob in the credential store under
    ``backend_id = "snaptrade"``.
    """

    client_id: str
    consumer_key: str
    user_id: str
    user_secret: str


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SnapTradeFetchReport:
    accounts_seen: int
    inv_txns_new: int
    inv_txns_duplicate: int
    positions_written: int
    securities_upserted: int
    duration_secs: float


# ---------------------------------------------------------------------------
# action_type → (trntype, income_type)
# ---------------------------------------------------------------------------

_ACTION_MAP: dict[str, tuple[str, str | None]] = {
    "BUY":             ("BUY",          None),
    "BUY_TO_OPEN":     ("BUY",          None),
    "SELL":            ("SELL",         None),
    "SELL_TO_CLOSE":   ("SELL",         None),
    "DIV":             ("INCOME",       "DIV"),
    "DIVIDEND":        ("INCOME",       "DIV"),
    "REINVEST":        ("REINVEST",     "DIV"),
    "DRIP":            ("REINVEST",     "DIV"),
    "CONTRIBUTION":    ("CONTRIBUTION", None),
    "DEPOSIT":         ("CONTRIBUTION", None),
    "WITHDRAWAL":      ("WITHDRAWAL",   None),
    "FEE":             ("FEE",          None),
    "MANAGEMENT_FEE":  ("FEE",          None),
    "TAX":             ("TAX",          None),
    "TRANSFER":        ("TRANSFER",     None),
    "JOURNAL":         ("TRANSFER",     None),
    "SPLIT":           ("SPLIT",        None),
}


# ---------------------------------------------------------------------------
# Normalization helpers
# ---------------------------------------------------------------------------


def _pick_security_id(sym: StSymbol) -> tuple[str, str]:
    """Return ``(uniqueid, uniqueid_type)`` using FIGI > CUSIP > ISIN > TICKER."""
    if sym.figi_code:
        return sym.figi_code, "FIGI"
    if sym.cusip:
        return sym.cusip, "CUSIP"
    if sym.isin:
        return sym.isin, "ISIN"
    return sym.symbol, "TICKER"


def _symbol_to_security(sym: StSymbol) -> Security:
    uniqueid, uniqueid_type = _pick_security_id(sym)
    return Security(
        uniqueid=uniqueid,
        uniqueid_type=uniqueid_type,
        name=sym.description or sym.symbol,
        ticker=sym.symbol,
        security_type="STOCK",  # SnapTrade doesn't reliably surface the security type
    )


def _date_str_to_epoch(d: str | None) -> int | None:
    if not d:
        return None
    try:
        parsed = date.fromisoformat(d)
        return int(datetime(parsed.year, parsed.month, parsed.day, tzinfo=timezone.utc).timestamp())
    except (ValueError, TypeError):
        return None


def _normalize_activity(act: StActivity) -> InvestmentTransaction:
    raw = act.action_type.upper()
    trntype, income_type = _ACTION_MAP.get(raw, ("OTHER", None))
    if trntype == "OTHER":
        log.warning("snaptrade unknown action_type=%r — mapped to OTHER", act.action_type)

    security_id: str | None = None
    security_id_type: str | None = None
    if act.symbol:
        security_id, security_id_type = _pick_security_id(act.symbol)

    trade_epoch = _date_str_to_epoch(act.trade_date)
    settle_epoch = _date_str_to_epoch(act.settlement_date)

    return InvestmentTransaction(
        id=act.id,
        trade_date=trade_epoch or 0,
        settle_date=settle_epoch,
        trntype=trntype,
        security_id=security_id,
        security_id_type=security_id_type,
        units=act.units,
        unit_price=act.price,
        commission=act.fee,
        fees=None,
        taxes=None,
        total=act.amount or Decimal("0"),
        income_type=income_type,
        description=act.description,
        memo="",
        currency=act.currency,
    )


def _normalize_position(pos: StPosition) -> Position | None:
    if pos.symbol is None:
        return None
    security_id, security_id_type = _pick_security_id(pos.symbol)
    return Position(
        security_id=security_id,
        security_id_type=security_id_type,
        units=pos.units,
        unit_price=pos.price or Decimal("0"),
        market_value=pos.market_value or Decimal("0"),
        cost_basis=pos.average_purchase_price,
        held_in_acct="CASH",
        pos_type="LONG",
        snapshot_date=int(time.time()),
    )


def _normalize_account(
    st_acct: StAccount,
    balance: StBalance,
    positions: list[StPosition],
    activities: list[StActivity],
    conn_id: str,
) -> InvestmentAccount:
    normalized_positions = tuple(
        p for p in (_normalize_position(pos) for pos in positions) if p is not None
    )
    normalized_txns = tuple(_normalize_activity(a) for a in activities)
    return InvestmentAccount(
        id=st_acct.id,
        name=st_acct.name or st_acct.number,
        currency=balance.currency,
        broker_id=conn_id,
        available_cash=balance.cash,
        margin_balance=None,
        balance_date=int(time.time()),
        conn_id=conn_id,
        positions=normalized_positions,
        investment_transactions=normalized_txns,
    )


def _windows(dtstart: int, dtend: int, window_secs: int) -> list[tuple[int, int]]:
    wins: list[tuple[int, int]] = []
    cur = dtstart
    while cur < dtend:
        end = min(cur + window_secs, dtend)
        wins.append((cur, end))
        cur = end
    return wins


# ---------------------------------------------------------------------------
# SnapTradeBackend
# ---------------------------------------------------------------------------


class SnapTradeBackend:
    """Owns the SnapTrade HTTP client and ``St*`` → neutral model conversion."""

    def __init__(
        self,
        credentials: SnapTradeCredentials,
        httpx_client: httpx.AsyncClient,
        *,
        activity_window_days: int = 90,
    ) -> None:
        self._activity_window_days = activity_window_days
        self._client = StClient(
            client_id=credentials.client_id,
            consumer_key=credentials.consumer_key,
            user_id=credentials.user_id,
            user_secret=credentials.user_secret,
            httpx_client=httpx_client,
        )

    async def fetch_and_persist(
        self,
        storage: Storage,
        *,
        tenant_id: str,
        dtstart_epoch: int,
        dtend_epoch: int | None = None,
    ) -> SnapTradeFetchReport:
        t0 = time.monotonic()
        end_anchor = dtend_epoch if dtend_epoch is not None else int(time.time())

        # 1. Brokerage authorizations → stable conn_id mapping
        auth_list: list[StBrokerageAuthorization] = (
            await self._client.get_brokerage_authorizations()
        )
        slug_map: dict[str, str] = {a.id: a.brokerage.slug for a in auth_list}

        # 2. Accounts
        st_accounts: list[StAccount] = await self._client.get_accounts()
        activities_by_account: dict[str, list[StActivity]] = {
            a.id: [] for a in st_accounts
        }

        # 3. Activities across date windows
        window_secs = self._activity_window_days * 86400
        wins = _windows(dtstart_epoch, end_anchor, window_secs)

        all_symbols: dict[str, StSymbol] = {}

        for win_start, win_end in wins:
            # Use UTC to avoid off-by-one on machines with non-UTC local time
            start_dt = datetime.fromtimestamp(win_start, tz=timezone.utc).date()
            end_dt = datetime.fromtimestamp(win_end, tz=timezone.utc).date()
            activities = await self._client.get_activities(start_dt, end_dt)
            log.info(
                "snaptrade activities start=%s end=%s count=%d",
                start_dt, end_dt, len(activities),
            )
            for act in activities:
                if act.account_id and act.account_id in activities_by_account:
                    activities_by_account[act.account_id].append(act)
                if act.symbol:
                    uid, _ = _pick_security_id(act.symbol)
                    all_symbols[uid] = act.symbol

        # Dedup activities within each account bucket by ID, preserving order.
        # Adjacent fetch windows use inclusive date ranges so the same activity
        # can appear in two consecutive windows.
        for acct_id, acts in activities_by_account.items():
            seen: dict[str, StActivity] = OrderedDict()
            for act in acts:
                if act.id not in seen:
                    seen[act.id] = act
            activities_by_account[acct_id] = list(seen.values())

        # 4. Balances, positions, and per-account assembly
        inv_accounts: list[InvestmentAccount] = []
        conn_map: dict[str, Connection] = {}

        for auth in auth_list:
            cid = normalize_conn_id(auth.brokerage.slug)
            if cid not in conn_map:
                conn_map[cid] = Connection(
                    conn_id=cid,
                    org_name=auth.brokerage.name,
                    org_id=auth.brokerage.id,
                )

        for st_acct in st_accounts:
            slug = slug_map.get(st_acct.brokerage_authorization_id, st_acct.institution_name)
            conn_id = normalize_conn_id(slug)

            balance = await self._client.get_account_balance(st_acct.id)
            positions = await self._client.get_positions(st_acct.id)

            for pos in positions:
                if pos.symbol:
                    uid, _ = _pick_security_id(pos.symbol)
                    all_symbols[uid] = pos.symbol

            inv_account = _normalize_account(
                st_acct,
                balance,
                positions,
                activities_by_account.get(st_acct.id, []),
                conn_id,
            )
            inv_accounts.append(inv_account)
            log.info(
                "snaptrade account name=%r conn_id=%s positions=%d txns=%d",
                st_acct.name, conn_id,
                len(inv_account.positions),
                len(inv_account.investment_transactions),
            )

        securities = tuple(_symbol_to_security(sym) for sym in all_symbols.values())

        chunk = StorageChunk(
            accounts=(),
            connections=tuple(conn_map.values()),
            investment_accounts=tuple(inv_accounts),
            securities=securities,
        )
        stats = storage.merge_chunk(tenant_id, chunk)

        return SnapTradeFetchReport(
            accounts_seen=stats.inv_accounts_seen,
            inv_txns_new=stats.inv_txns_new,
            inv_txns_duplicate=stats.inv_txns_duplicate,
            positions_written=stats.positions_written,
            securities_upserted=stats.securities_upserted,
            duration_secs=time.monotonic() - t0,
        )


__all__ = ["SnapTradeFetchReport", "SnapTradeBackend", "SnapTradeCredentials"]
